import React from 'react'
import Head from 'next/head'
import { Contacto } from '/src/components/Contacto/index.jsx'
import { NuestraFilosofia } from '/src/components/NuestraFilosofia/index.jsx'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Abiagus Turismo | Excursiones en Mendoza</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel='shortcut icon'
          href='/media/icon/favicon.ico'
        />
      </Head>
      <main>
        <section className={styles.section__main} rel='preload'>
          <h1>ABIAGUS</h1>
          <h2>SERVICIOS TURÍSTICOS</h2>
        </section>
        <NuestraFilosofia />
        <section className={styles.section__phase} rel='preload'>
          <p>"EL VINO ES MAGIA, TRABAJO Y PASIÓN, VENÍ A MENDOZA Y DESCUBRÍ CUÁL ES PARA VOS"</p>
        </section>
        <Contacto />
      </main>
    </>
  )
}