import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
//import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Abiagus Turismo | Excursiones en Mendoza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/media/icon/favicon.ico" onload="this.rel='stylesheet'"/>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="robots" content="index, follow" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Anton&family=Roboto+Condensed:wght@400;700&display=swap" rel="stylesheet" />
      </Head>
      <main>
        <h1>Abiagus Turismo</h1>
      </main>
    </>
  )
}
